Integration File,Start Date Time,Status,Description,End Date Time,Duration in Seconds,Rows Updated,Rows Created
eloqua_accounts.py,2021-11-16 10:59:57.189288,Pass,Successful Run,2021-11-16 11:00:15.837330,18.648042,5,20
eloqua_bounceback.py,2021-11-16 10:59:56,Fail,"(psycopg2.errors.DuplicateTable) relation ""t_eloqua_bounceback"" already exists

[SQL: CREATE TABLE customer360.t_eloqua_bounceback AS (SELECT * FROM customer360.s_eloqua_bounceback WHERE 1=2);]
(Background on this error at: http://sqlalche.me/e/f405)",2021-11-16 10:59:56,0,0,0
eloqua_contacts.py,2021-11-16 11:00:22.602743,Pass,Successful Run,2021-11-16 11:00:45.961460,23.358717,599,398
eloqua_emailclickthrough.py,2021-11-16 11:00:45.977085,Pass,Successful Run,2021-11-16 11:01:10.648243,24.671158,0,430
eloqua_emailopen.py,2021-11-16 11:01:10.663871,Pass,Successful Run,2021-11-16 11:01:53.381414,42.717543,0,16498
eloqua_emailsend.py,2021-11-16 11:01:53.397039,Pass,Successful Run,2021-11-16 11:02:56.129597,62.732558,0,50885
eloqua_formsubmit.py,2021-11-16 11:02:56.145224,Pass,Successful Run,2021-11-16 11:03:28.331807,32.186583,0,425
eloqua_pageview.py,2021-11-16 11:03:28.347431,Pass,Successful Run,2021-11-16 11:03:50.893638,22.546207,0,3332
eloqua_subscribe.py,2021-11-16 11:03:50.909263,Pass,Successful Run,2021-11-16 11:04:04.346398,13.437135,0,255
eloqua_unsubscribe.py,2021-11-16 11:04:04.346398,Pass,Successful Run,2021-11-16 11:04:10.908691,6.562293,0,255
eloqua_webvisit.py,2021-11-16 11:04:10.924315,Pass,Successful Run,2021-11-16 11:04:33.470562,22.546247,0,1204
salesforce_account.py,2021-11-16 11:04:33.970526,Pass,Successful Run,2021-11-16 11:04:56.610482,22.639956,94,41
salesforce_campaign.py,2021-11-16 11:04:56.626106,Pass,Successful Run,2021-11-16 11:05:17.641136,21.01503,152,19
salesforce_campaignmember.py,2021-11-16 11:05:17.656757,Pass,Successful Run,2021-11-16 11:06:24.014237,66.35748,3769,25379
salesforce_case.py,2021-11-16 11:06:24.014237,Pass,Successful Run,2021-11-16 11:06:53.388410,29.374173,4258,1398
salesforce_contact.py,2021-11-16 10:59:56,Fail,'DataFrame' object has no attribute 'MailingAddress',2021-11-16 10:59:56,0,0,0
salesforce_event.py,2021-11-16 11:06:56.747659,Pass,Successful Run,2021-11-16 11:07:20.825093,24.077434,103,106
salesforce_lead.py,2021-11-16 11:07:20.825093,Pass,Successful Run,2021-11-16 11:07:33.621592,12.796499,645,357
salesforce_opportunity.py,2021-11-16 11:07:33.637219,Pass,Successful Run,2021-11-16 11:08:07.636236,33.999017,411,31
salesforce_recordtype.py,2021-11-16 11:08:07.651864,Pass,Successful Run,2021-11-16 11:08:27.510706,19.858842,116,0
salesforce_task.py,2021-11-16 11:08:27.526289,Pass,Successful Run,2021-11-16 11:08:53.558625,26.032336,1054,6342
salesforce_user.py,2021-11-16 11:08:53.558625,Pass,Successful Run,2021-11-16 11:11:03.553047,129.994422,127927,110
